version: "2"

tasks:
  default:
    cmds:
      - task: run

  clean:
    desc: Clean project
    cmds:
      - rm -rf ./build

  test:
    desc: Test project
    cmds:
      - go test -cover ./...

  security:
    desc: Run gosec for project
    cmds:
      - gosec -quiet ./...

  run:
    desc: run everything
    cmds:
      - task: clean
      - task: security
      - task: test
