on: push
name: Testing Go Code
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run tests
      uses: cedrickring/golang-action@1.6.0
      with:
        args: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      env:
        GO111MODULE: "on"